# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e3ab8c7f4d84521114da1c02f49c07c5aa7947e1eeb9bdba49aaa300a5baf2b1ea4e26d22bf82d1e81455bc2345239312f4ae99695cb01158ca86fd7d7c9b5

test:
  secret_key_base: f70803adea0dbc78a976e705cbf8b1ba6403769c100521947ca33c5458daf9957ac9e86a6dee0b9ec0ad2703dfdec7995cdbb9a9f8e5870f1fc140c32eb44577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
